### ISSUE TITLE
Locating coral data in www.africanmarineatlas.org/

### ISSUE THREAD

**Issue by WIOSymphony** [iodepo/odis-arch#133]
The African Marine Atlas seemingly holds some unique data not found elsewhere.

As an example the following dataset about coral reefs is sought after by the WIO Symphony project:
africanmarineatlas.org   Overlays/data/Madagascar/Biosphere/Marine habitats/Reef system 2008 

![coral_capture](https://user-images.githubusercontent.com/91244852/199251908-89ed7aea-4d5f-40f4-b4ca-317bae3330d3.JPG)

WIO Symphony project strives to locate and put best available data to work for MSP in the WIO region creating composite maps of  ecosystem components as well as human activities and pressures.

**Comment by jmckenna** [comment]
Thanks for this report @WIOSymphony 

I've begun digging into this.  (I now have access to the internal VPN network, but I am awaiting access to this specific machine)

As an aside, I notice the associated MapServer layer name (small world, I'm the MapServer release manager ha) is `mg_reef-Madagascar`, and I can successfully load that WMS layer in QGIS (the endpoint to use for that WMS service is http://www.africanmarineatlas.org/server/mapserver/wms.php? )

Will keep you posted here of progress.

**Comment by jmckenna** [comment]
@WIOSymphony sorry for the delay (I just solved accessing the old server today).  Here is the shapefile data associated with that layer (note that the app classifies this data through the `CLASSE` field) : http://www.africanmarineatlas.org/tmp/test_recif-p_dd.tar.gz

**Comment by WIOSymphony** [comment]
@jmckenna thank you for this effort to make more data on corals available. Data downloaded and tested, it shows new reef areas not found in other maps and can to some extent be verified by observations of reef from high resolution satellite imagery. To increase usefulness, is there metadata of any kind showing where this layer is from and what went into the classification of the different classes?
