### ISSUE TITLE
OceanExpert: sitemap errors

### ISSUE THREAD

**Issue by jmckenna** [iodepo/odis-arch#149]
- discovered through @fils' [check_sitemap](https://github.com/gleanerio/scheduler/blob/master/tooling/sitemapCheck/check_sitemap_loop.py) script 
- OE sitemap index appears empty: https://oceanexpert.org/assets/sitemaps/sitemapIndex.xml
- `robots.txt` points to that sitemap index: https://oceanexpert.org/robots.txt

**Comment by jmckenna** [comment]
setting this now as a blocker, as OceanExpert sitemap errors prevent their indexing into ODIS.

**Comment by fils** [comment]
@jmckenna @arnounesco 

Jeff,   I think you have conflated   EurOcean and Ocean Experts in your sources file?

Could you check all those entries again. Some are correct, others look like you typed in oceanexperts for them.

Also, Arno isn't the contact for EurOcean (correct @arnounesco ?)   It should be these people https://eurocean.org/  (they oddly use .org and .net it seems like)

```
#
# EurOcean Training
#    
- name: euroceantraining
  propername: EurOcean Training 
  domain: https://infohub.eurocean.net/
  catalogue: https://infohub.eurocean.net/data/training 
  logo: https://infohub.eurocean.net/images/under_constrution/eurOcean-logo-color.png  
  #ODISCat entry missing ODIS-arch url & type
  pid: https://catalogue.odis.org/view/2993  
  sourcetype: sitemap
  url: https://www.oceanexpert.org/assets/sitemaps/sitemapTraining.xml
  changefreq: unknown  
  backend: unknown  
  headless: false
  dateadded: 2022-03-26  
  active: true  
```

**Comment by jmckenna** [comment]
Indeed I believe I have never been introduced to the EurOcean partner (I have had no contact with them).  I believe the meetings happened in 2021.  Those 5 sitemap links I found in one of the Notebooks (I also thought it was odd, OceanExpert sitemap urls for EurOcean projects).  I see an email for a contact in the partner spreadsheet, I'll email them now...

**Comment by jmckenna** [comment]
I've updated the description of this ticket (for the OceanExpert empty sitemap issue), and created a new ticket for EurOcean : (177)

**Comment by arnounesco** [comment]
fixed, was a permission issue after checkout for new version, seems like execution permission was gone
done for experts, training, events, institutions

**Comment by jmckenna** [comment]
Confirmed, thanks @arnounesco   (tested with the sitemapChecker now: 34466 valid records in sitemap)
