### ISSUE TITLE
Hub Ocean krill metadata

### ISSUE THREAD

**Issue by TaraOceanData** [iodepo/odis-arch#176]
Hi, per our discussion in our meeting, here is the information on the metadata for the raw krill files.

The dataset metadata will follow [schema.org's dataset schema](https://schema.org/Dataset)
(This has not been filled out yet)

The searchable raw sonar files will populate the 'distribution' field and that metadata would look like this:

```json
{
    "name": "D20220226-T144737.raw",
    "mime_type": "text/plain",
    "size_bytes": 54960000,
    "metadata": {
        "krill.akerbiomarine.com/vessel": "Saga Sea",
        "krill.akerbiomarine.com/sonarModel": "ES80",
        "krill.akerbiomarine.com/sonarType": "echosounder",
        "krill.akerbiomarine.com/frequencies": "[38, 120]",
        "krill.akerbiomarine.com/surveyTime": "2022-02-26T14:47:37",
        "krill.akerbiomarine.com/startTime": "2022-02-26 14:47:37.473999872",
        "krill.akerbiomarine.com/endTime": "2022-02-26 15:01:23.320000"    },
    "geo_location": "POINT (-45.70008 -60.04339)"}
```

**Comment by jmckenna** [comment]
Thank-you @TaraOceanData for providing this sample.

**Comment by fils** [comment]
Pushed up this branch related to the above example:
https://github.com/iodepo/odis-arch/tree/176-Hub-Ocean-krill-metadata

This is the file we edited:
https://github.com/iodepo/odis-arch/blob/176-Hub-Ocean-krill-metadata/book/thematics/dataset/graphs/krillMetadata.json

**Comment by jmckenna** [comment]
Closing this ticket as the krill metadata sample pattern is available in our [master branch](https://github.com/iodepo/odis-arch/blob/master/book/thematics/dataset/graphs/krillMetadata.json), and further Hub Ocean<->ODIS discussions will occur through #310
