### ISSUE TITLE
 odis-arch/schema/thematics/training/ organizer

### ISSUE THREAD

**Issue by arnounesco** [iodepo/odis-arch#18]
in OceanExpert we do not have a real provider for a training but rather organizers, how do we fit this in?

**Comment by pbuttigieg** [comment]
Hi @arnounesco - wasn't there an OE calendar of trainings mentioned in our thematic meeting on this? That would be the most natural link. 

Aside from that, OE Organization IDs (or Individual IDs) could be used as a valid input to identify providers of trainings

**Comment by arnounesco** [comment]
we have the trainings info, but within that training info there is no notion of the concept 'provider', the best I can find is an organizer, which is a person or a list of persons.
I did understand that 'provider' is rather an institute/organization.
I created the sitemap for training https://www.oceanexpert.org/assets/sitemaps/sitemapTraining.xml and there is JSON-LD in the training pages.

**Comment by wardappeltans** [comment]
Jumping in if useful. The participants list in OE has categories for instructors and learners. E.g https://www.ioc-cd.org/index.php?option=com_oe&task=viewEventParticipants&eventID=2118

**Comment by fils** [comment]
@arnounesco 

I was able to harvest the sitemap once I addresses the hard returns.  However, now this is raising on issue in the JSON-LD.

Take the resource https://www.oceanexpert.org/event/10

Do a view source and copy the JSON-LD in the page into the playground at https://json-ld.org/playground/#startTab=tab-expanded

You should see the errors in the JSON-LD coming from the hard returns.  You can remove them there and test there too.
Can these be easily removed in your publishing process?

Google seems to do fine with it.  https://search.google.com/structured-data/testing-tool#url=https%3A%2F%2Fwww.oceanexpert.org%2Fevent%2F10  (where they get their recommended and required from I'd love to know).

**Comment by arnounesco** [comment]
solved and tested
removed all the newlines in all txt fields

**Comment by fils** [comment]
@arnounesco 
Progress.  I can now get about 400 indexed.   

The next issue I am hitting is that you have quotations in some of the strings.   So look at the JSON-LD in https://www.oceanexpert.org/event/236.  The descriptions has quotes in it.  These need to be removed or escaped out with a back slash.  

We need to arrive at a best way to deal with quotations in JSON strings.  It might be  the backslash escape, but we should verify that is the best way in JSON-LD.

**Comment by arnounesco** [comment]
Just hit the same problem while making the JSON for the documents.
Will fix this tomorrow if that is ok for you?

**Comment by pieterprovoost** [comment]
@arnounesco Shouldn't your serializer take care of all these quirks like linebreaks and quotes automatically?

**Comment by arnounesco** [comment]
no serializer here, twig template, maybe have to change that

**Comment by arnounesco** [comment]
double quotes are escaped, https://www.oceanexpert.org/event/236 passed the JSON playground
