### ISSUE TITLE
autors/contributors for creativeWork/docs

### ISSUE THREAD

**Issue by arnounesco** [iodepo/odis-arch#19]
don't we need a place for the authors/contributors in https://github.com/iodepo/odis-arch/tree/master/schema/thematics/docs

**Comment by fils** [comment]
Thanks!   see https://github.com/iodepo/odis-arch/tree/schema-dev/schema/thematics/docs  and let me know what you think.

**Comment by arnounesco** [comment]
look good to me, thd
