### ISSUE TITLE
spatial features

### ISSUE THREAD

**Issue by pieterprovoost** [iodepo/odis-arch#2]
Some resources:

- https://github.com/internetofwater/geoconnex.us/issues/16#issuecomment-621406552
- https://github.com/ESIPFed/science-on-schema.org/
- https://www.ogc.org/blog/2215
- https://schema.org/geo
- [Springer Handbook of Geographic Information](https://www.springer.com/gp/book/9783540726784), see chapter 15. Geosemantic Interoperability and the Geospatial Semantic Web

**Comment by skybristol** [comment]
Not sure where this one is going either. @pieterprovoost, you are a master of the minimalist GitHub issue. :-)

It seems like one of the things we need to work out with the ODIS architecture will be how we tap into the many of different sources of spatial feature information ODIS-powered systems need to take advantage of. A core principle should be not reinventing any wheels but leveraging as many other assets as we can. Some of your references seem to be getting at that dynamic.

One applicable source of important spatial features that ODIS might help broker for broad use is the [Global Shorelines/Islands](https://rmgsc.cr.usgs.gov/gie/) stuff from Roger Sayre and others. The interesting ODIS dynamic here might be providing the basis for systems and system developers to understand the various sources of the same type information, under what circumstances each may be useful, and some notion over time of who in the ODIS network is using what.

Is that sort of registry and tracking mechanism for ocean-related spatial features the type of thing that you were thinking about here?

**Comment by pieterprovoost** [comment]
Sorry, I was just throwing out some bait as this place felt a bit empty :fish: I guess the point of this issue is to get a feel for the variety of spatial data sources and standards that ODIS will need to deal with. Most of the information we are interested in will have a spatial component (datasets, observing systems, projects, experts, vessels, platforms, publications, etc), either explicitly or by linking to gazetteers and other spatial repositories, and filtering content by region will be an important cpability of the system.
