### ISSUE TITLE
remove book/_build from repo

### ISSUE THREAD

**Issue by pieterprovoost** [iodepo/odis-arch#37]
As we are building the book using Actions we probably want to leave out the `_build` directory?

**Comment by fils** [comment]
Good point....

If I just add it to .gitignore that should do it?    

So it's ignored and a new one is built doing the git actions then it sounds like.

**Comment by pieterprovoost** [comment]
I tink it's best to explicitely remove and commit first, then add to .gitignore.

Optionally we can remove it from the git history altogether using [BFG](https://rtyley.github.io/bfg-repo-cleaner/).
