### ISSUE TITLE
Create "Getting Started with ODIS" guide

### ISSUE THREAD

**Issue by pbuttigieg** [iodepo/odis-arch#379]
A new page in the ODIS Book where partners can get a general overview of how to link their system to ODIS. 

This should cover:
- Creating and managing organisational identity in OceanExpert (including cleaning up legacy content)
- Creating and managing data nodes in ODISCat
- Developing ODIS Arch content using the Book
- Creating and registering their sitemap.xml (with update frequency for config)
- Triggering indexing and verifying content in OIH.

**Comment by pbuttigieg** [comment]
@fils @jmckenna 

I'll lay out the skeleton and some text for this. Please add links to the appropriate documentation and resource pages (e.g. our OGTA content) where needed. 

You can also add that in a list so I can work them in to the text as it develops

**Comment by pbuttigieg** [comment]
Ensure this guide is circulated to all IODE projects, sub-components, NODCs, ADUs, etc

**Comment by jmckenna** [comment]
- useful SPARQL queries to add to the guide: https://api.triplydb.com/s/XMKVjO9-l

**Comment by Lucy-Scott** [comment]
The guide should be as simple as possible - where longer descriptions or side stories are needed, it should link to text / definitions in the Book

**Comment by Lucy-Scott** [comment]
For example, the starting outline can be exactly what Jeff sends to partners:

GETTING STARTED
- create an entry in the ODIS Catalogue https://catalogue.odis.org/
 - login with your OceanExpert ID
 - important fields are
       - Startpoint URL for ODIS-Arch (this is the url to your
sitemap.xml file)
       - Type of the ODIS-Arch URL (select "Sitemap")

embed JSON-LD on each record page in the catalogue
*→ Modify ViewMetadata page to generate and include JSON-LD for each
metadata entry*
create a sitemap.xml pointing to each record, and place the
sitemap on the web
*→ Create sitemap.xml including links to all metadata entries*
*→ Modify AddMetadata, UpdateMetadata, DeleteMetadata pages to update
the sitemap.xml on changes*

**Comment by jmckenna** [comment]
update:
- there was already a nice template for the `gettingStarted.md` in the root of the book directory ([here](https://github.com/iodepo/odis-arch/blob/master/book/gettingStarted.md)), I will combine the other `getting-started.Md` (from [here](https://github.com/iodepo/odis-arch/pull/380)), into this `gettingStarted.md` in the root of the book directory.   Sorry for this confusion!
