### ISSUE TITLE
Make "book.odis.org" the official home

### ISSUE THREAD

**Issue by jmckenna** [iodepo/odis-arch#455]
- I'm starting to see the url https://book.odis.org mentioned in official IODE documents
- the old url ( https://book.oceaninfohub.org/ ) should therefore redirect to book.odis.org
  - it currently does the opposite

cc @pbuttigieg @arnounesco

**Comment by arnounesco** [comment]
fixed
DNS changed for book.odis.org to cname to github
DNS changed for book.oceaninfohub.org to cname to an internale webserver with redirect to book.odis.org
server config changed for gettingstartedwith.odis.org to redirect to book.odis.org
changed github setting to accept book.odis.org as domain

**Comment by tchaddad** [comment]
Hi all:
FYI, at least as of today, https://book.odis.org/ is giving a 404 @ GitHub Pages.

**Comment by arnounesco** [comment]
should be fixed
GitHub changed the setting for the page after I changed it....no idea why we host pages on GitHub, not my thing :-(

can you please check and close if ok?

**Comment by jmckenna** [comment]
thanks both, I confirm that it is working now

**Comment by jmckenna** [comment]
I have also changed the url link in the right panel for "About" at https://github.com/iodepo/odis-arch

**Comment by jmckenna** [comment]
@arnounesco I notice that my old bookmark of https://book.oceaninfohub.org/index.html now redirects to a broken link: https://book.odis.orgindex.html/

**Comment by jmckenna** [comment]
@arnounesco could you do the same for the dashboard?  
 - old: **dashboard.oceaninfohub.org**
 - new: **dashboard.odis.org**

**Comment by arnounesco** [comment]
the link has never been https://book.oceaninfohub.org/index.html as far as I know, it should be https://book.oceaninfohub.org and pointing to https://book.odis.org
I'll change the redirect anyhow to match that but cannot garantee that the https://book.odis.org/index.html will exist as this is a GitHub thing out of my controll

**Comment by jmckenna** [comment]
@arnounesco the link used to exist (see [here](https://web.archive.org/web/20220327000150/https://book.oceaninfohub.org/index.html) for a WaybackMachine's view of that url on 2022-03-27

Confirmed the fix.

(related: yesterday I also [corrected the CNAME](https://github.com/iodepo/odis-arch/commit/9b0b60f83a4ce4a2406204c01b7765c9a98c1248) in our automated GitHub Action, which was causing the auto-publish to break each time, likely why I saw in the logs that you have recently had to manually re-deploy the Github Pages site, each time)

Closing.

**Comment by arnounesco** [comment]
thx for fixing that, was not aware of this setting

**Comment by adamml** [comment]
I know this issue is closed, but as a lurker I remembered seeing it in the last few weeks...

This morning https://book.odis.org/ is giving a "site can't be reached" error for me.

**Comment by jmckenna** [comment]
@adamml sorry I was offline when you reported this.  It seems fine now but will keep a close eye on it.
