### ISSUE TITLE
Website BUG: Link to ODIS Architecture Documentation on ODIS About page is broken

### ISSUE THREAD

**Issue by MathewBiddle** [iodepo/odis-arch#459]
Not sure if this is the right place to post this issue. Feel free to move as necessary.

The ODIS about page (https://odis.org/about/) references to the [ODIS architecture documentation](https://book.oceaninfohub.org/index.html), but that link is broken. I think it should be pointing to https://book.odis.org/.

**Comment by arnounesco** [comment]
should be fixed, can you please check again and close if ok?

**Comment by MathewBiddle** [comment]
Yup, Fixed on my end! Thanks for the quick response.
