### ISSUE TITLE
Person/nationality

### ISSUE THREAD

**Issue by smrgeoinfo** [iodepo/odis-arch#469]
at https://book.odis.org/thematics/expinst/index.html#details-nationality Example at   uses 'DefinedTerm' to associate with name from a vocabulary, but this throws and error in Schema.org validator.  Would it make more sense to use nationality/Country/identifier:

```
{
    "@context": {
        "@vocab": "https://schema.org/"
    },
    "@id": "https://example.org/permanentUrlToThisJsonDoc",
    "@type": "Person",
    "nationality": [
        {
            "@type": "Country",
            "name": "Fiji",
             "identifier":
                     {  "@type": "PropertyValue",
                        "name": "Fiji",
                        "value": "FJ",
                        "propertyID": ["https://unece.org/trade/cefact/unlocode-code-list-country-and-territory","ISO 3166-1:2020"]            
                    }    
           }
      ]  }
```

this validates at https://validator.schema.org/

**Comment by jmckenna** [comment]
Fixed through https://github.com/iodepo/odis-in/commit/2b9b13ac4eccafa97a3c1983b52471f773254e9c

The changes are now visible in the Book at https://book.odis.org/thematics/expinst/index.html#details-nationality

thanks @smrgeoinfo
