### ISSUE TITLE
Issue on page /thematics/expinst/README.html : expert nationality

### ISSUE THREAD

**Issue by arnounesco** [iodepo/odis-arch#47]
the expert information is lacking the notion of nationality which will be needed if regional hubs want to extract only experts in their region
I propose to add https://schema.org/nationality to https://schema.org/Person

**Comment by fils** [comment]
@arnounesco 

like with language this is a great addition..  I worked up

https://book.oceaninfohub.org/thematics/expinst/README.html#details-nationality

please review and let me know what you think...

**Comment by arnounesco** [comment]
perfect, this is what I implemented
