### ISSUE TITLE
add teams to GitHub settings

### ISSUE THREAD

**Issue by jmckenna** [iodepo/odis-arch#59]
- background: I'd like to be added into the GitHub 'team' for ODIS-arch
- I believe we should setup a "Developers" team in the GitHub settings at https://github.com/iodepo/odis-arch/settings/access
  - see "Manage Access" section there, and click "Create team"
    - likely select "Write" as the role for this team, as it allows "Can read, clone, and push to this repository. Can also manage issues and pull requests"

(the admin of iodepo/odis-arch will likely have to set this up, as I don't have permissions currently, I manually wrote the url above from a different project)

**Comment by pieterprovoost** [comment]
I'm not sure we need a team if we are just working on this one repository, but I'll set one up. Until now we only added individual contributors.

**Comment by jmckenna** [comment]
@pieterprovoost ok whatever you think is best.  I just thought teams was the usual way to handle different permissions for different groups.  Thanks for enabling this, I received and accepted the invite.  Closing.
