### ISSUE TITLE
create Dashboard to monitor ODIS nodes

### ISSUE THREAD

**Issue by jmckenna** [iodepo/odis-arch#60]
- example dashboard: https://dashboard.obofoundry.org/dashboard/index.html (ODIS partners could be the rows, columns could be the monitored items)
- goal would be to generate a simple interface to display a live view of ODIS statistics, to track the status of OIH partners
- tracked items could be:
  - number of nodes active in OIH
  - percentage of possible data patterns implemented by partners
  - types of thematic patterns available (projects, training, vessels, etc) by partner
  - number of active nodes by region
- This same dashboard could also show usage activity in terms of:
  - number of indexed records (or catalogues) by ODIS, for a partner or geographical region
  - last index time of partner's services, by ODIS
  - common search (query) terms submitted (to the ODIS graph)
- Another possibility is to use this same dashboard for:
  - monitoring of partner's endpoint services (is their catalogue service available, show a big green checkmark, if not available show a big yellow question mark, and on mouse-over show when service last available)
  - view of usual web server statistics for specific ODIS urls, such as number of visits, geographic region, etc.
- Notifications could be enabled for this dashboard
  - daily/weekly/monthly report could be auto-generated and sent to team
  - notices could be sent when services are down/not available (on the partner side and the ODIS-side, as both will have problems at some point)
- Important discussion topic could be what information is private, and what tracked info should be kept as a backend admin view of this dashboard.  

 (all of above are just ideas, recorded here initially as a way to throw-ideas-on-the-whiteboard, and each part is fine to remove or add)  Goal here is to start the discussion/planning through this ticket.

Screen capture from example site mentioned above:
![dashboard-odis](https://user-images.githubusercontent.com/1611709/154332344-50814c44-88ab-4626-b5b6-9bbeaf1d9d9a.png)

**Comment by fils** [comment]
Let's look at streamlit on Friday and some of the SPARQL queries I have that do some of this already

**Comment by jmckenna** [comment]
(from my notes, a topic I meant to bring up today but did not) I wonder if we can track (on this dashboard?) or encourage partners to generate a DOI for their data services.  (I am aware that JSON-LD does have an ID field for this)

Background: on the open software side, there has been a big push to get all software releases their own generated DOI.  I've set this up now for several projects recently (eg. PostGIS: https://doi.org/10.5281/zenodo.5879631     MapServer: https://doi.org/10.5281/zenodo.5842012 )  This can all be automated.

I wonder how we can recommend this to ODIS nodes/partners.

This could be an old topic here for you all, I realize.  

To discuss on Friday.

**Comment by jmckenna** [comment]
From recent discussions:
- there is a strong need to also track the search terms used through the ODIS portal, into the graph
- the Dashboard could include a portal section that could parse the server logs and query for the list of search terms
  - this came up in early discussions by jeff & doug, about the need to monitor the status of the nodes, and parsing the server logs (daily or a few times a week) might be very helpful

**Comment by jmckenna** [comment]
- View of recent updates to Dashboard (includes querying for the date-added-to-graph).   Demo:  http://catalogue.gatewaygeo.ca:8501/odis/dashboard/

  (or screenshot of interface) :
![dashboard-update-2022-07-20](https://user-images.githubusercontent.com/1611709/180053470-c9eb7fac-e87b-47e3-ad56-3588cd02136f.png)

- Dashboard code lives in `schema-dev` branch at https://github.com/iodepo/odis-arch/tree/schema-dev/code/notebooks/Exploration/dashboard

- comments:
  - already running into issues of matching the `orgname` set inside the graph, with the `propername` set in `oihSources.csv`, etc.

**Comment by jmckenna** [comment]
Closing this ticket, as Dashboard was created. (issues with the Dashboard are being created separately)
